services:
  todoapp-postgres:
    image: postgres:18.4-bookworm
    container_name: todoapp-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 3s
      retries: 30

  todoapp-postgres-migrate:
    image: migrate/migrate:v4.19.1
    depends_on:
      todoapp-postgres:
        condition: service_healthy
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: todoapp-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:todoapp-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pgdata: