FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/todoapp ./cmd/todoapp

FROM alpine:latest
WORKDIR /app

# Required for migrate tool or any ca-certs
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/todoapp .
COPY --from=builder /app/migrations ./migrations

EXPOSE 8080
CMD ["./todoapp"]
